export { Aspectra } from '#aspectra'
export { autobind } from '#decorators/autobind'
export { bound } from '#decorators/bound'
export { Container } from '#container'
export { Context } from '#context'
export { contextualized } from '#decorators/injection/contextualized'
export { main } from '#decorators/main'
export { memoize } from '#decorators/memoize'
export { sealed } from '#decorators/sealed'
export { singleton } from '#decorators/singleton'
export { provide } from '#decorators/injection/provide'
export { provider } from '#decorators/injection/provider'

export type { Identifier, PrimitiveIdentifier } from '#types/identifier'
