name: Release Preview
on:
  - push
  - pull_request

jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - run: pnpm --frozen-lockfile install
      - run: pnpm --recursive --filter ./packages/* test
      - run: pnpm --recursive --filter ./packages/* build
      - run: pnpm pkg-pr-new publish --compact ./packages/*
