name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      increment:
        required: true
        description: "Select the version increment type"
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - run: release-it ${{ inputs.increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
