name: Release Preview
on:
  - push
  - pull_request

jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - run: pnpm test
      - run: pnpm build
      - run: pnpm pkg-pr-new publish --compact
