name: Release Preview

on:
  - push
  - pull_request

jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: pnpm test
      - run: pnpm build
      - run: pnpm pkg-pr-new publish --pnpm --compact ./packages/*
