name: Snapshot

on:
  - push
  - pull_request

jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm test
      - run: pnpm build
      - run: pnpm pkg-pr-new publish --pnpm --compact ./packages/*
