name: Test

on:
  - push
  - pull_request

jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm -r type-check
      - run: pnpm test
